//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogbookZeroAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogItem
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public string AircraftType { get; set; }
        public string AircraftRegistration { get; set; }
        public string Position { get; set; }
        public string FromCode { get; set; }
        public string ToCode { get; set; }
        public Nullable<decimal> SingleEngineDayPilot { get; set; }
        public Nullable<decimal> SingleEngineDayDual { get; set; }
        public Nullable<decimal> SingleEngineNightPilot { get; set; }
        public Nullable<decimal> SingleEngineNightDual { get; set; }
        public Nullable<decimal> MultiEngineDayPilot { get; set; }
        public Nullable<decimal> MultiEngineDayDual { get; set; }
        public Nullable<decimal> MultiEngineDayCopilot { get; set; }
        public Nullable<decimal> MultiEngineNightPilot { get; set; }
        public Nullable<decimal> MultiEngineNightDual { get; set; }
        public Nullable<decimal> MultiEngineNightCopilot { get; set; }
        public Nullable<decimal> CrossCountryDayPilot { get; set; }
        public Nullable<decimal> CrossCountryDayDual { get; set; }
        public Nullable<decimal> CrossCountryNightPilot { get; set; }
        public Nullable<decimal> CrossCountryNightDual { get; set; }
        public Nullable<decimal> InstrumentHood { get; set; }
        public Nullable<decimal> InstrumentCloud { get; set; }
        public Nullable<decimal> InstrumentSim { get; set; }
    }
}
